homeassistant:
  #  name: Home
  #  latitude: !secret home_latitude
  #  longitude: !secret home_longitude
  #  elevation: 60
  #  unit_system: metric
  #  time_zone: Europe/Stockholm
  customize: !include customize.yaml

default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 172.17.232.0/24
    - 192.168.1.0/24
    - 127.0.0.1

discovery:

lovelace:

# ShellyForHACS
shelly:
  version: true
  sensors:
    - all

# Text to speech
tts:
  - platform: google_translate

# RFXtrxXL
rfxtrx:
  device: /dev/ttyUSB0
  devices:
    0b110000000186aa01000060:
    #      name: Lampslinga trappa
    0b11000300018e8401000060:
    #      name: Fönsterlampa vardagsrum
    0b11000700030e6c03000060:
    #      name: Hängande lampa Lous rum
    0b11000900030e0802000060:
    #      name: Lampslinga Lous rum
    0b11000c000186b401000060:
    #      name: Växtbelysning gästrum
    0b11000e000186c102000060:
    #      name: Fönsterlampa sovrum
    0b11001300030d4001000070:
    #      name: Växtbelysning uppe
    0b11001703ba1b4e0e010f60:
    #      name: Utebelysning
    0a14114f0004e401010050:
    #      name: Utebelysning slingor
    0b11001a00018e8e01000070:
    #      name: Bokhyllsbelysning Lous rum
    0b1100210173baaa10000060:
    #      name: Balkongdörr
    0b110000024fc2aa10010f50:
#      name: Ytterdörr

# Tellstick DUO
tellstick:
  host: local-tellstick
  signal_repetitions: 3
  port: [50800, 50801]

sensor:
  # växelriktare boningshus
  - platform: huawei_solar
    host: "192.168.1.116"
    #optimizers: true
    #battery: true
    slave: 1
    #port: 6607
  # växelriktare garage
  - platform: huawei_solar
    host: "192.168.1.115"
    #optimizers: true
    #battery: true
    slave: 1
    #port: 6607
  - platform: tellstick
    temperature_scale: "°C"
  #    only_named:
  #      - id: 135
  #        name: KitchenInside
  #      - id: 136
  #        name: KitchenOutside
  #      - id: 151
  #        name: UpstairsInside
  #      - id: 152
  #        name: UpstairsOutside
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      #      - type: processor_use
      - type: load_1m
      - type: load_5m
      - type: processor_use
      - type: last_boot
  #  - platform: rest
  #    resource: https://api.github.com/rate_limit
  #    name: Github HACS
  #    value_template: '{{ value_json.resources.core.used }}'
  #    headers:
  #      Authorization: !secret github-access-token
  #      Accept: application/vnd.github.v3+json
  #      Content-Type: application/json
  #      User-Agent: Home Assistant REST sensor
  - platform: integration
    source: sensor.ftx_fan_power_2
    name: ftx_fan_total_consumption
    unit_prefix: k
    round: 2
  - platform: fusion_solar_kiosk
    kiosks:
      - url: !secret fusion_solar_kiosk_url
        name: "Saturnusvägen 2"
  - platform: greenely
    email: !secret greenely_email
    password: !secret greenely_password
    facility_id: !secret greenely_facility_id
    hourly_usage: true
    sold: true
    sold_daily: true

template:
  - sensor:
      - name: "Current consumption garage radiators"
        unit_of_measurement: "W"
        state: "{{ states('sensor.shelly_shplg_s_bc1996_current_consumption') | float(0) + states('sensor.shelly_shplg_s_e43e3a_current_consumption') | float(0) + states('sensor.shelly_shplg_s_ea99cc_current_consumption') | float(0) }}"
        device_class: power
  - sensor:
      - name: "Total consumption garage radiators"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.shelly_shplg_s_e43e3a_total_consumption') | float(0) + states('sensor.shelly_shplg_s_ea99cc_total_consumption') | float(0) + states('sensor.shelly_shplg_s_e43e3a_total_consumption') | float(0) }}"
        device_class: energy
  - sensor:
      - name: "Daily consumption increasing"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.greenely_daily_usage') | float }}"
        device_class: power
        state_class: total_increasing

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

alert: !include alerts.yaml
